<nav>
  <ul>
    <li><a href="index.php" <?php echo ($activePage === 'index') ? 'class="active"' : ''; ?>>Home</a></li>
    <li><a href="jobs.php" <?php echo ($activePage === 'jobs') ? 'class="active"' : ''; ?>>Job Descriptions</a></li>
    <li><a href="apply.php" <?php echo ($activePage === 'apply') ? 'class="active"' : ''; ?>>Job Application</a></li>
    <li><a href="about.php" <?php echo ($activePage === 'about') ? 'class="active"' : ''; ?>>About Us</a></li>
    <li><a href="enhancements.php" <?php echo ($activePage === 'enhancements') ? 'class="active"' : ''; ?>>Enhancements</a></li>
    <li><a href="enhancements2.php" <?php echo ($activePage === 'enhancements2') ? 'class="active"' : ''; ?>>Enhancements II</a></li>
    <li><a href="phpenhancements.php" <?php echo ($activePage === 'enhancements3') ? 'class="active"' : ''; ?>>Enhancements III</a></li>
    <li><a href="mailto:103503191@student.swin.edu.au">Contact Us</a></li>
    <li><a href="login.php" <?php echo ($activePage === 'login') ? 'class="active"' : ''; ?>>My Manager</a></li>
  </ul>
</nav>
